version: "3.1"

services: 
 db:
    image: mariadb
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: msa
    volumes: 
      - ./mariadb_home:/var/lib/mysql